name: Download Release

on:
  push:
    branches: [ "main" ]
env: 
  GH_API_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      
      - name: Download release
        run: |
          curl -LX GET https://github.com/CanarysPlayground/PartsUnlimited/releases/download/v1.1/spacegameleaderboard.zip \
                --header "Accept: application/vnd.github.v3+json" \
                --header "Authorization: Bearer ${GH_API_TOKEN}" \
                -O
      - name: list files
        run:  |
         ls -ltr 
     
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: Release-artifact
          path: .
          
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'Release-artifact'
      
