name: Download Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      
      - name: Download release
        run: |
          curl -LX GET https://github.com/CanarysPlayground/PartsUnlimited/releases/download/v1.1/spacegameleaderboard.zip \
                --header "Accept: application/vnd.github.v3+json" \
                --header "Authorization: Bearer 
                  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}" \
                -O
