name: Download Release

on:
  push:
    branches: [ "main" ]
env: 
  GH_API_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      
      - name: Download release
        run: |
          curl -LX GET https://github.com/CanarysPlayground/PartsUnlimited/releases/download/v1.1/spacegameleaderboard.zip \
                --header "Accept: application/vnd.github.v3+json" \
                --header "Authorization: Bearer ${GH_API_TOKEN}" \
                -O
      - name: list files
        run:  |
         ls -ltr 
  
  Create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3    
    - uses: octokit/request-action@v2.x
      id: create_release
      with:
        route: POST /repos/CanarysPlayground/repo-template1/releases
        tag_name: v1.1.4
        GITHUB_TOKEN: ${{secrets.PAT_TOKEN}}   
   
    - uses: cb80/pubrel@latest
      with:
         replace: latest
         files: |
           spacegameleaderboard.zip
          
#       - name: moving a dir 
#         run: |
#           mkdir artifact
#           mv spacegameleaderboard.zip artifact
          
          
#       - name: Upload the artifacts
#         uses: skx/github-action-publish-binaries@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           args: 'artifact'
        

