name: Download Release

on:
  push:
    branches: [ "main" ]
env: 
  GH_API_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:    
   
  Create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3    
    - uses: octokit/request-action@v2.x
      id: create_release
      with:
        route: POST /repos/ramesh2051/Git-LFS/releases
        tag_name: v1.7
        GITHUB_TOKEN: ${{secrets.NEW_TOKEN}}   
   
   
    - name: Download release
      run: |
          curl -LX GET https://github.com/Playground-demo/deepspace/releases/download/1.0/spacegameleaderboard.zip \
                --header "Accept: application/vnd.github.v3+json" \
                --header "Authorization: Bearer ${GH_API_TOKEN}" \
                -O
    - name: list files
      run:  |
         ls -ltr 
         
#     - name: Upload release    
    - uses: cb80/pubrel@latest
      with:
         replace: v1.7
         files: |
           spacegameleaderboard.zip
          

