name: Download Release

on:
  push:
    branches: [ "main" ]
env: 
  GH_API_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      
      - name: Download release
        run: |
          curl -LX GET https://github.com/CanarysPlayground/PartsUnlimited/releases/download/v1.1/spacegameleaderboard.zip \
                --header "Accept: application/vnd.github.v3+json" \
                --header "Authorization: Bearer ${GH_API_TOKEN}" \
                -O
      - name: list files
        run:  |
         ls -ltr 
         
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
         repo_token: ${{ secrets.PAT_TOKEN }}
         file: ${{github.workspace}}/spacegameleaderboard.zip
         asset_name: test-release
         tag: 1.1.3
         overwrite: true
         body: "This is my release text"
      
